#!/bin/bash

# Run multi-gadget setup script.
sudo /home/pi/uvc-gadget/multi-gadget.sh

# Set some camera control options.
/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=8
/usr/bin/v4l2-ctl -c contrast=20
/usr/bin/v4l2-ctl -c video_bitrate=25000000

# For 4K resolution (3840x2160):
sudo /home/pi/uvc-gadget/uvc-gadget -f1 -s1 -r2 -u /dev/video1 -v /dev/video0 -w 3840 -h 2160

# For Full HD resolution (1920x1080):
sudo /home/pi/uvc-gadget/uvc-gadget -f1 -s1 -r1 -u /dev/video1 -v /dev/video0 -w 1920 -h 1080
