#!/bin/bash

# Run multi-gadget setup script.
sudo /home/pi/uvc-gadget/multi-gadget.sh

# Set some camera control options.
/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=8
/usr/bin/v4l2-ctl -c contrast=20
/usr/bin/v4l2-ctl -c video_bitrate=25000000

# For 1600x1200 (WIDTH1, HEIGHT1):
sudo /home/pi/uvc-gadget/uvc-gadget -f1 -s1 -r0 -u /dev/video1 -v /dev/video0 -w 1600 -h 1200

# For 1920x1080 (WIDTH2, HEIGHT2):
 sudo /home/pi/uvc-gadget/uvc-gadget -f1 -s1 -r1 -u /dev/video1 -v /dev/video0 -w 1920 -h 1080
